title: singerng.github.io
description: Noah Singer's personal website and blog.

email: singerng@gmail.com
username: singerng
url: https://singerng.github.io

markdown: kramdown
kramdown:
  input: GFM
  mathjax: true
  syntax_highlighter: rouge

sass:
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock

timezone: America/New_York

titles_from_headings:
  collections: true
  strip_title: true

plugins:
  - jekyll-titles-from-headings
